export const DARK_MODE_ENABLED = 'DARK_MODE_ENABLED';
export const FILTERED_ALBUMS_BY_YEAR = 'FILTERED_ALBUMS_BY_YEAR';
export const ALBUM_TAGS = 'ALBUM_TAGS';
export const FEATURED_ALBUMS = 'FEATURED_ALBUMS';
export const ALBUMS_WITH_LOCATION = 'ALBUMS_WITH_LOCATION';
export const TRAVEL_RECORDS = 'TRAVEL_RECORDS';
