org: bluegray
app: quasar-photo-albums
service: quasar-photo-album-lambda
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-plugin-typescript

functions:
  app:
    handler: src/app.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    environment:
      AWS_REGION_NAME: ${self:provider.region}
      GOOGLE_PLACES_API_KEY: ${param:GOOGLE_PLACES_API_KEY}
      GOOGLE_CLIENT_ID: ${param:GOOGLE_CLIENT_ID}
      ALBUM_URL: ${param:ALBUM_URL}
      IMAGEKIT_CDN_URL: ${param:IMAGEKIT_CDN_URL}
      AWS_S3_BUCKET_NAME: ${param:AWS_S3_BUCKET_NAME}
      PHOTO_ALBUMS_TABLE_NAME: ${param:PHOTO_ALBUMS_TABLE_NAME}
      PHOTO_ALBUM_TAGS_TABLE_NAME: ${param:PHOTO_ALBUM_TAGS_TABLE_NAME}
      PHOTO_USER_PERMISSION_TABLE_NAME: ${param:PHOTO_USER_PERMISSION_TABLE_NAME}
      JWT_SECRET: ${param:JWT_SECRET}
package:
  patterns:
    - '!.env.example'
    - '!.eslintrc.js'
    - '!.gitignore'
    - '!package-lock.json'
    - '!tsconfig.json'
    - '!tsconfig.dev.json'
