name: Build and deploy demo web app

on:
  pull_request:
    branches:
      - master
    paths:
      - "src/**"
  workflow_dispatch:
    inputs:
      buildManually:
        description: 'Run build manually'
        required: true
        default: 'build'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_FOR_GITHUB_DEPLOY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_FOR_GITHUB_DEPLOY }}
      VITE_ALBUM_APP_TITLE: ${{ vars.VITE_ALBUM_APP_TITLE }}
      VITE_STATIC_FILES_URL: ${{ vars.VITE_STATIC_FILES_URL }}
      VITE_IMAGEKIT_CDN_URL: ${{ vars.VITE_IMAGEKIT_CDN_URL }}
      VITE_MAPBOX_API_KEY: ${{ secrets.VITE_MAPBOX_API_KEY }}
      VITE_AWS_API_GATEWAY_URL: ${{ vars.VITE_AWS_API_GATEWAY_URL }}
      VITE_MAP_CENTRE_LNG: ${{ vars.VITE_MAP_CENTRE_LNG }}
      VITE_MAP_CENTRE_LAT: ${{ vars.VITE_MAP_CENTRE_LAT }}
      VITE_GTAG_ID: ${{ secrets.VITE_GTAG_ID }}"

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install

      - name: Write .env file
        run: |
          tee .env <<EOF
          VITE_ALBUM_APP_TITLE=$VITE_ALBUM_APP_TITLE
          VITE_STATIC_FILES_URL=$VITE_STATIC_FILES_URL
          VITE_IMAGEKIT_CDN_URL=$VITE_IMAGEKIT_CDN_URL
          VITE_MAPBOX_API_KEY=$VITE_MAPBOX_API_KEY
          VITE_AWS_API_GATEWAY_URL=$VITE_AWS_API_GATEWAY_URL
          VITE_GOOGLE_CLIENT_ID=DEMO_GOOGLE_CLIENT_ID
          VITE_MAP_CENTRE_LNG=$VITE_MAP_CENTRE_LNG
          VITE_MAP_CENTRE_LAT=$VITE_MAP_CENTRE_LAT
          VITE_GTAG_ID=DEMO_GTAG_ID
          EOF

      - name: Test and build
        run: |
          bun run type-check
          bun run test:unit
          bun run build

      - name: Clean up old files
        uses: keithweaver/aws-s3-github-action@master
        with:
          command: rm
          source: s3://${{ vars.AWS_S3_BUCKET_NAME }}/assets/
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_FOR_GITHUB_DEPLOY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_FOR_GITHUB_DEPLOY }}
          aws_region: us-east-1
          flags: --recursive

      - name: Upload to S3
        uses: keithweaver/aws-s3-github-action@master
        with:
          source: dist
          destination: s3://${{ vars.AWS_S3_BUCKET_NAME }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_FOR_GITHUB_DEPLOY }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_FOR_GITHUB_DEPLOY }}
          aws_region: us-east-1
          flags: --recursive

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: /
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_FOR_GITHUB_DEPLOY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_FOR_GITHUB_DEPLOY }}
